config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#index'
  get '/about', to: 'homes#about'
  devise_for :users
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint(8)        not null, primary key
#  title      :string(255)      not null
#  content    :text(65535)      not null
#  user_id    :bigint(8)        not null
#  created_at :datetime         not null
#  updated_at :datetime         not null


class Post < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true, length: { minimum: 10 }
  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint(8)        not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string(255)      not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, uniqueness: true, presence: true
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
    @posts = Post.all
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "ブログを投稿しました"
      redirect_to 'index'
    else
      flash[:error] = "投稿は作成されませんでした"
      render :new
    end
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def show
    @post = Post.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    @post = attribute(post_params)
    if @post.update(post_params)
      redirect_to :action => 'index'
    else
      render :edit
    end
  end

  def destroy
    flash[:success] = 'ストーリーを削除しました'
    @post = current_user.posts.find(params[:id])
    @post.destroy
    redirect_to :action => 'index'
  end

  private

    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def after_sign_up_path_for(resource)
    # サインアップ後のリダイレクト先をrootに変更
    root_path
  end

  def after_update_path_for(resource)
    user_path(current_user)
  end

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/homes/about.html.erb
<h1>Homes#about</h1>
<p>Find me in app/views/homes/about.html.erb</p>

app/views/homes/index.html.erb
<head>
  <div class="top-image-wrapper">
    <%= image_tag("/assets/top-image.png", class: "top-image") %>
    <h1 class="top-title">Memolog</h1>
  </div>
  <div class="center">
    <p class="sub-title">メモのように、ブログを書こう。</p>
  </div>
</head>
<section class="services">
  <h2 class="center about">ABOUT SERVICES</h2>
  <div class="script center">
    <p>メモのように気軽な気分でブログを書くサービスです。好きな時間に、好きな場所で、好きな話題を。</p>
    <p>モバイルファーストでありながら、高機能なエディタ機能も実装しています。</p>
    <p>余計な機能を排除し、シンプルな設計で開発しました。</p>
  </div>
  <div class="center">
  <%= image_tag("/assets/editor.png", class: "editor-image") %>
  </div>
</section>

<section class="dev">
  <h2 class="center aboutdev">ABOUT DEV.</h2>
  <div class="center">
  <%= image_tag("/assets/dev.jpg", class: "dev-image") %>
  </div>
  <div class="script center">
    <p>このサービスは個人開発者である<a href="https://twitter.com/tyengineer">＠TYengineer</a>によって開発・運用されています。</p>
    <p>個人故に起きるバグや不具合等ございましたら、ご連絡下さい。</p>
  </div>
</section>

<footer>
  <div class="center">
    <p>Memolog©️</p>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://fonts.googleapis.com/earlyaccess/kokoro.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Spicy+Rice" rel="stylesheet">

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'partial/navigation'%>
    <%= render 'partial/nav2' %>
    <%= render 'partial/notification' %>
    <%= yield %>
  </body>
</html>

app/views/partial/_nav2.html.erb
<nav>
  <ul class="nav-items">
    <li class="nav-item"><a href="#"><i class="fa fa-home"></i>Memolog</a></li>
    <li class="nav-item"><a href="#"><i class="fa fa-file"></i> 投稿する</a></li>
    <li class="nav-item"><a href="#"><i class="fa fa-cogs"></i></a></li>
  </ul>
</nav>

app/views/partial/_navigation.html.erb
<!-- the trigger -->
<div class="curtain-menu-button" data-curtain-menu-button>
  <div class="curtain-menu-button-toggle">
    <div class="bar1"></div>
    <div class="bar2"></div>
  </div>
</div>

<!-- the menu  -->
<div class="curtain-menu">
  <div class="curtain"></div>
  <div class="curtain"></div>
  <div class="curtain"></div>
  <div class="curtain-menu-wrapper">
    <ul class="curtain-menu-list menu vertical">
      <li><a href="/">ホーム</a></li>
      <li><a href="/about">このサービスについて</a></li>
      <% if user_signed_in? %>
        <li><%= link_to "ブログを書く", new_post_path %></li>
        <li><%= link_to "ブログを読む", posts_path %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path %></li>
      <% else %>
        <li><%= link_to "会員になる", new_user_registration_path %></li>
        <li><%= link_to "ログイン", new_user_session_path %></li>
      <% end %>      
    </ul>
  </div>
</div>

<script>
  $('[data-curtain-menu-button]').click(function(){
    $('body').toggleClass('curtain-menu-open');
  })
</script>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<h2 class="center">ブログ投稿一覧</h2>

<% @posts.each do |post| %>
  <div class="center card-content">
    <%= link_to(post_path(post.id), class: "post-link") do %>
    <%= image_tag("/assets/eyecatch.png", class: "blog-image") %>
    <h3 class="post-title"><%= "#{post.title}" %></h3>
    <div class="post-script">
      <%= truncate(strip_tags(post.content), length: 100) do %>
        <p><%= link_to('続きを読む', post_path(post.id), class: "next-link") %></p>
      <% end %>
    </div>
    <% end %>
  </div>
<% end %>

app/views/posts/new.html.erb
<div class="edit-parent">
  <%= form_for @post do |f| %>
    <div class="form-group center">
      <%= f.text_field :title, class: "form-control title-form", placeholder: 'ブログタイトル' %>
    </div>
    <div class="form-group">
        <%= f.text_area :content, size: "60x12", class: 'floara-editor', id: 'froala' %>
    </div>
    <div class="center">
      <%= f.submit "投稿する", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<h1 class="post-title"><%= @post.title %></h1>
<%= (sanitize @post.content).html_safe %>